### ISSUE TITLE
Compile error using make 4.2.1

### ISSUE THREAD

**Issue by rstegm** [lpgaff/MiniballCoulexSort#1]
When trying to compile I always get the following error:

make -C common
make[1]: Verzeichnis „/home/robert/IS546-2017/pcepisdaq6/MiniballCoulexSort/common“ wird betreten
/usr/bin/g++-5 -O2 -pipe -Wall -W -Woverloaded-virtual -I./ -c CommandLineInterface.cc -o CommandLineInterface.o
ar cru ../lib/libCommandLineInterface.a CommandLineInterface.o
ar: 'u' modifier ignored since 'D' is the default (see 'U')
rm CommandLineInterface.o
make[1]: Verzeichnis „/home/robert/IS546-2017/pcepisdaq6/MiniballCoulexSort/common“ wird verlassen
make -C MedToRoot
make[1]: Verzeichnis „/home/robert/IS546-2017/pcepisdaq6/MiniballCoulexSort/MedToRoot“ wird betreten
make[2]: Verzeichnis „/home/robert/IS546-2017/pcepisdaq6/MiniballCoulexSort/common“ wird betreten
/usr/bin/g++-5 -O2 -pipe -Wall -W -Woverloaded-virtual -I./ -c CommandLineInterface.cc -o CommandLineInterface.o
ar cru ../lib/libCommandLineInterface.a CommandLineInterface.o
ar: 'u' modifier ignored since 'D' is the default (see 'U')
rm CommandLineInterface.o
make[2]: Verzeichnis „/home/robert/IS546-2017/pcepisdaq6/MiniballCoulexSort/common“ wird verlassen
/usr/bin/g++-5 -O2 -pipe -Wall -W -Woverloaded-virtual -pthread -m64 -I/opt/root-5.34.36/include/root -fPIC -I./med/inc -I../common -I../mbevts -I./ MedToRoot.cc BuiltEvent.o Datas.o EventBuffer.o EventBuilder.o GlobalSettings.o Modules.o SubEvents.o UnpackedEvent.o ./med/mbsio.o ./med/byte_order.o ../common/CommandLineInterface.o MedToRootDictionary.o -lm -L/opt/root-5.34.36/lib/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic -L../lib -lCommandLineInterface -o MedToRoot
g++-5: Fehler: ../common/CommandLineInterface.o: Datei oder Verzeichnis nicht gefunden
make[1]: *** [Makefile:50: MedToRoot] Fehler 1
make[1]: Verzeichnis „/home/robert/IS546-2017/pcepisdaq6/MiniballCoulexSort/MedToRoot“ wird verlassen
make: *** [Makefile:10: MedToRoot] Fehler 2

I'm using Arch Linux with gcc 7.2.0, make 4.2.1, Root 5.34.36. At least this specific version of make seems to remove CommandLineInterface.o after executing common/Makefile because it is not mentioned explicitly as a target. Reverting to common/Makefile of commit 19b9202 solved this problem for me.

**Comment by lpgaff** [comment]
Fixed in the latest push to git
